[package]
name = "ngtq"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A trait-based abstraction layer for task queues with ID and category support"
repository = "https://github.com/yourusername/ngtq"
documentation = "https://docs.rs/ngtq"
readme = "README.md"
license = "MIT"
keywords = ["queue", "task-queue", "abstraction", "message-bus", "async"]
categories = ["concurrency", "api-bindings"]
rust-version = "1.70.0"

include = [
    "src/**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE",
]

exclude = [
    ".git",
    ".github",
    "target",
]

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]